basemore = "http://www.thiagoazeredo.com"
baseurl = "http://thiagoribeiro.github.io"
languageCode = "en-us"
title = "Thiago Azeredo`s personal page"
theme = "thiagoazeredo"

[params]
title = "Creative software engineer, passionate developer."
subtitle = ""
mail = "dev@thiagoazeredo.com"
tags= [
        "C#",
        "NODEJS",  
        "C/C++",
        "PYTHON",  
        "PHP", 
        "HTML", 
        "JAVASCRIPT", 
        "CSS", 
        "Arduino", 
        "Xamarin", 
        "Android", 
        "Apache", 
        "NGINX", 
        "Oracle", 
        "MySQL", 
        "SQLite", 
        "Postgree", 
        "MongoDB",
        "AWS",
        "GTK",
        "Linux",
        "Docker",
        "WPF",
        "Angular",
        "JQuery"]
    
[params.about]
    description =  "M Sc software engineer with more than 12 years experience working with different programming languages and databases, in Windows and Linux environment.     I have designed, developed and produced numerous softwares and actualy working on software that allows to manage the offshore work with focus on improve  operation and security."
    [[params.about.skill]]
    name = "Coding"
    note = 9
    [[params.about.skill]]
    name = "Architecture"
    note = 7
    [[params.about.skill]]
    name = "Self learning"
    note = 8
    [[params.about.skill]]
    name = "Team work"
    note = 9
    [[params.about.skill]]
    name = "Creativity"
    note = 9
    [[params.about.skill]]
    name = "Organization"
    note = 6
    
    
[[params.projects]]
    title = "Chomsky´s Regular Grammar generator"
    description="A didactic word generator using the rules of the type 3 of Chomsky's theory, created to assist in my Theory of Computation classes."
    technologies="C# WPF"
    image = "img/study.svg"
    more = "https://github.com/thiagoribeiro/GeradorPalavrasChomskyTipo3"
[[params.projects]]
    title = "PyKillerBlock"
    description="A pythonic version of classic 'break the wall' game created with educational intentions."
    technologies="Python Pygame"
    image = "img/study.svg"
    more = "https://github.com/thiagoribeiro/pyKillerBlock"
[[params.projects]]
    title = "Virtual Wheel"
    description="My master´s project. System that uses stereoscopy able to recognize both hands simulating holding a steering wheel and replicates the movements for a racing game.  [![IMAGE ALT TEXT](http://img.youtube.com/vi/ijpovMsPSxk/0.jpg)](https://www.youtube.com/watch?v=ijpovMsPSxk \"See here\")"
    technologies="C++ Ogre3D CUDA Socket Pipeline-processing OpenCV"
    image = "img/book.svg"
    more = "https://github.com/thiagoribeiro/Volante-Virtual"
    
[[params.projects]]
    title = "Karacol concierge"
    description="A concierge proprietary system created to serve a Brazilian region"
    technologies="PHP MySQL SphinxSearch"
    image = "img/sphere.svg"
    url = "http://www.karacol.com.br"

[[params.projects]]
    title = "Working hours registration"
    description="![Project screenshot](img/working_hours.png) In the company I work, I need to access every day the company's site to register the entry and exit times of work, in addition to the lunch hour. I decided to create a small app for Android to do it for me with just one touch. Unfortunately the company not authorized to publish the  app in play store."
    technologies="Xamarin Android"
    image = "img/android.svg"
    
#[[params.projects]]
#    title = "C# Pdf Helpers for iTextSharp"
#    description="bla lblada dkja kdhasdhjadkjh dhajdk ahhd kjahdak dhad jahdhakdkbla lblada dkja kdhasdhjadkjh dhajdk ahhd kjahdak dhad jahdhakdk"
#    technologies="dsa kjdaldjalk dajdladja"
#    image = ""
#[[params.projects]]
#    title = "This page"
#    description="bla lblada dkja kdhasdhjadkjh dhajdk ahhd kjahdak dhad jahdhakdkbla lblada dkja kdhasdhjadkjh dhajdk ahhd kjahdak dhad jahdhakdk"
#    technologies="dsa kjdaldjalk dajdladja"
#    image = ""
#[[params.projects]]
#    title = "Job Scheduler"
#    description="bla lblada dkja kdhasdhjadkjh dhajdk ahhd kjahdak dhad jahdhakdkbla lblada dkja kdhasdhjadkjh dhajdk ahhd kjahdak dhad jahdhakdk"
#    technologies="dsa kjdaldjalk dajdladja"
#    image = ""
#[[params.projects]]
#    title = "Simple factory"
#    description="bla lblada dkja kdhasdhjadkjh dhajdk ahhd kjahdak dhad jahdhakdkbla lblada dkja kdhasdhjadkjh dhajdk ahhd kjahdak dhad jahdhakdk"
#    technologies="dsa kjdaldjalk dajdladja"
#    image = ""
#[[params.projects]]
#    title = "NHibernate instance"
#    description="bla lblada dkja kdhasdhjadkjh dhajdk ahhd kjahdak dhad jahdhakdkbla lblada dkja kdhasdhjadkjh dhajdk ahhd kjahdak dhad jahdhakdk"
#    technologies="dsa kjdaldjalk dajdladja"
#    image = ""
  
#[[params.projects]]
#    title = "Chomsky´s Regular Grammar generator"
#    description="bla lblada dkja kdhasdhjadkjh dhajdk ahhd kjahdak dhad jahdhakdkbla lblada dkja kdhasdhjadkjh dhajdk ahhd kjahdak dhad jahdhakdk"
#    technologies="dsa kjdaldjalk dajdladja"
#    image = ""
    